app/__init__.py
from flask import Flask
from app.blueprints import home_page
from app.blueprints import about
from app.blueprints import file_upload

app=Flask(__name__)

app.register_blueprint(file_upload.bp)
app.register_blueprint(home_page.bp)
app.register_blueprint(about.bp)


if(__name__=='__main__'):
    app.run(debug=True)

app/blueprints/about.py
from flask import Flask ,Blueprint,render_template,redirect,url_for

bp=Blueprint("about",__name__)

@bp.route('/about/')
def about():
    return render_template("about.html")

@bp.route('/about/name/')
def about_name():
    return redirect(url_for('about.think'))


@bp.route('/about/help/')
def help():
    return redirect(url_for("home_page.career")) 
#blueprint_name . function_name will work for redirecting the route


@bp.route('/about/think/')
def think():
    return render_template("static_page.html")

app/blueprints/file_upload.py
import pandas as pd
import os
import uuid
from flask import Flask, Blueprint,redirect,request,render_template,send_from_directory

bp=Blueprint("file_upload",__name__)

@bp.route('/')
def index():
    return render_template("file_upload.html")

@bp.route('/file',methods=["POST","GET"])
def file():
    file= request.files['file']
    if file.content_type=='text/plain':
        return file.read().decode()
    elif file.content_type=='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'or file.content_type=='application/vnd.ms-excel':
        df=pd.read_excel(file)
        return df.to_html()
    else:
        return "Error in uploading"

@bp.route('/csv/',methods=['GET','POST'])
def csv():
    file2=request.files['file2']#got the file form the html page in using the name tag
    dataframe=pd.read_excel(file2) #convert it to dataframe 
    if not os.path.exists('app/Downloads'):  #creation of the new folder using the os module if not exists
        print('creating downloading folder')
        os.makedirs('app/Downloads')
    filename=f'{uuid.uuid4()}.csv' #created the filename 
    dataframe.to_csv(os.path.join('app/Downloads',filename)) #conversion of the data frame to csv file 
    return render_template('download.html',filename=filename) #redirecting to the download.html page and passes filename to the html page

#the download.html page has redirected here but the path has filename in it so use the <> to get the dynamic file name     
@bp.route('/download/<path:filename>',methods=['GET'])
def download(filename):
    print(filename)
    #return f"{filename}"
    df=pd.read_csv(f'app/Downloads/{filename}')#reading the csv file from the downloads
    return df.to_html() #returning the csv file content in html page as table 

#unable to create a download link for the file 
#return send_from_directory('Downloads',filename)
# return send_from_directory('Downloads',filename)
# return send_from_directory('Downloads',filename,download_name='results.csv')
# return send_from_directory('Downloads',filename,download_name=f'{uuid.uuid4()}.csv')

app/blueprints/home_page.py
from flask import Flask,Blueprint,request,render_template

bp=Blueprint("home_page",__name__) #home_page is the blueprint name we initilized the blueprint name

@bp.route('/homepage/')
def homepage():
    if 'username' in request.args.keys() and 'password' in request.args.keys() and 'list' in request.args.keys() :
        username=request.args['username']
        password=request.args['password']
        list=request.args['list']
        #print(type(request.args['list']))#string
        # return f"home page username={username} password={password}"
        return render_template('/home_page.html',username=username,password=password,list=list)
    else:
        # return render_template('/static_page.html')
        return "default page"

@bp.route('/homepage/file?')

# @bp.route('/about',methods=['GET','POST','PUT','DELETE'])
# def about():
#     if request.method=='GET':
#         print("get")
#         return "get method"

#     elif request.method=='Post':
#         print("post")
#         return "post method"

#     elif request.method=='PUT':
#         print("put")
#         return "put method"
#     elif request.method=='DELETE':
#         print("delete")
#         return "delete method"
#     else:
#         print("other")
#     return "about page"

@bp.route('/career')
def career():
    # return render_template('static_page.html')
    return "default page"

app/templates/about.html
{% extends "base.html" %}
{% block title %} About page {% endblock %}
{% block content %}
<h1>About page</h1>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{%endblock%} </title>
</head>
<body>
  {% block content %}
  {% endblock %}

    
</body>
</html>

app/templates/download.html
{% extends "base.html" %}
{% block title%}download page{% endblock%}
{%block content%}
<h1>Download page</h1>
<!-- got the file form the python file using the jinja template and link tag redirecting the user back to the the download route and passing back the file name  -->
<a href="{{ url_for('file_upload.download',filename=filename) }}">Download Files</a>
{%endblock%}

app/templates/file_upload.html
{%extends "base.html"%}

{%block title%}File upload{% endblock %}

{%block content %}
<h1>Upload Your File</h1>
<form action="{{url_for('file_upload.file')}}" method="post" enctype="multipart/form-data">
    <input type="file" name="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/plain"><br><br>
    <button type="submit">Upload</button>
</form>

<form action="{{url_for('file_upload.csv')}}"method="post" enctype="multipart/form-data">
    <input type="file" name="file2" required accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel"><br><br>
    <button type="submit">upload file to download</button>
</form>
{% endblock %}

app/templates/home_page.html
{% extends "base.html" %}

{% block title %} home_page {% endblock %}

{% block content %}

<h1>Home page</h1>
<h2>block working</h2>
<br>
<h3>{{username}}</h3>
<h3>{{password}}</h3>
<h3>{{list}}</h3>

{% endblock %}

app/templates/static_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>static page</title>
</head>
<body>
    <h1>Invalid query parameter passed</h1>    
</body>
</html>